### ISSUE TITLE
accept nested forms

### ISSUE THREAD

**Issue by plentz** [CWSpear/angular-form-errors-directive#1]
if you have a form inside a form(using `ng-form`, for example), form errors show just the name of the form instead of each field of that form.

**Comment by CWSpear** [comment]
There was a scoping issue! I fixed it and added some extra functionality:

You can also specify a `form` name on the `formErrors` directive so that you don't _have_ to embed this directive in a `form`/`ngForm`. Setting a form in the `form` attribute will take precedence over inheriting from the form it's embedded in.

I also added an `formNiceName` attribute that you can put on an `ngForm` so that the parent form can output a message such as "Embedded Form has errors."

So check out `v1.1.0` and the expanded demo and see if that doesn't take care of your issue.
